services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "4321:4321"
      # - "3000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development

 